### ISSUE TITLE
couldn't find file 'jquery.ui.all'

### ISSUE THREAD

**Issue by harssh** [spree-contrib/spree_fancy#134]
Facing this issue on fresh install 

![screenshot from 2015-01-20 19 28 36](https://cloud.githubusercontent.com/assets/2812994/5818307/a4d5c0f4-a0da-11e4-9ff2-1244ecf0ece0.png)

Gemfile

source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'spree', github: 'spree/spree', branch: '2-3-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-3-stable'
gem 'spree_drop_ship', github: 'jdutil/spree_drop_ship', branch: '2-3-stable'
gem 'spree_marketplace', github: 'jdutil/spree_marketplace'
gem 'spree_fancy', :github => 'spree/spree_fancy', :branch => '2-3-stable'
gem 'quiet_assets'

**Comment by jaiwil1221** [comment]
Any have a fix to this?

**Comment by harssh** [comment]
@jaiwil1221 I have made a PR for this for 2-3-stable branch it fixes error #135

**Comment by futhr** [comment]
It has been fixed now with #135 for `2-3-stable` branch.

**Comment by mdk55** [comment]
Sorry? How is this fixed -- I get this error on a fresh install as well ??
