### ISSUE TITLE
Revert spree_fancy installation

### ISSUE THREAD

**Issue by bmurtagh** [spree-contrib/spree_fancy#136]
Hey all,

I screwed up and accidentally installed spree_fancy preemptively and would like the revert the installation and migrations, but I'm unsure of the exact steps. Any guidance is appreciated.

Thanks

**Comment by JDutil** [comment]
Reverse what this does:
https://github.com/spree-contrib/spree_fancy/blob/master/lib/generators/spree_fancy/install/install_generator.rb

i.e. remove the asset manifest references, and rollback / delete the migrations.
