### ISSUE TITLE
Spree fancy is not compatible with Spree 3-0-stable

### ISSUE THREAD

**Issue by rsempe** [spree-contrib/spree_fancy#139]
The latest version of Spree is 3-0-stable.

The dependency is Spree Core 2.3.0 https://github.com/spree-contrib/spree_fancy/blob/908732bc8050a08e2c95dba2170dc16ba9c5699c/spree_fancy.gemspec#L18

**Comment by JDutil** [comment]
Don't count on this being updated unless you'd like to contribute the pull request.  Spree no longer uses the skeleton framework this is based upon.
